R_max:
  R_max: 1
  exploration_timesteps: 1e4
  num_iterations: 100
  exploration_threshold: 10


data_collect:
  env_name: MiniGrid-Empty-8x8-v0 #MiniGrid-Dynamic-Obstacles-8x8-v0 # Name of environment, or comma-separate list of environment names to instantiate as each env in the VecEnv.
  visualize: False # to choose whether your want to see the env during interaction or not
  episodes: 200 # number of episodes to start 
  collect:
    data_train: ${oc.env:TRAIN_DATASET_PATH}/gridworld_Rmax.npz # folder where to save the rollouts
    visit_count: ${oc.env:TRAIN_DATASET_PATH}/visit_count_Rmax.npz # folder where to save the rollouts

world_model:
  model: 'Rmax'
  map_width: 3
  map_height: 3 # for this version, extract the square position centered at the agent 
  action_size: 1 # dimension of the action space
  batch_size: 128
  n_cpu: 8
  hidden_size: 256 #hidden size
  data_dir: ${oc.env:TRAIN_DATASET_PATH}/gridworld_Rmax.npz
  n_epochs: 50 # number of training epochs
  obs_size: 27 # the env for Rmax height * width * channels = 12 * 6 * 3
  lr: 1e-3
  wd: 1e-5
  pth_folder: ${oc.env:PTH_FOLDER}/Rmax/wm_rmax-epoch=41-avg_val_loss_wm=0.0006.ckpt
  # pth_folder: ${oc.env:PTH_FOLDER}/Rmax/world_model_Rmax.ckpt
  obs_norm_values: [10, 5, 3]
  action_norm_values: 6
  valid_values_obj: [1, 2, 4, 5, 8, 10]
  valid_values_color: [0, 1, 5]
  valid_values_state: [0, 1, 2, 3]

PPO:
  has_continuous_action_space: False
  max_ep_len: 1000  # max timesteps in one episode
  action_std: 0.1  # set same std for action distribution which was used while saving
  i_episode: 0
  K_epochs: 80  # update policy for K epochs
  eps_clip: 0.2  # clip parameter for PPO
  gamma: 0.99  # discount factor
  lr_actor: 0.0003  # learning rate for actor
  lr_critic: 0.001  # learning rate for critic
  checkpoint_path: ${oc.env:PTH_FOLDER}/policy_model_Rmax.ckpt
  time_step: 0
  max_training_timesteps: 5.2e5
  # max_training_timesteps: 3e5
  action_std_decay_freq: 2.5e5
  action_std_decay_rate: 0.05
  min_action_std: 0.1
  save_model_freq: 2e4
  render: True
