data_generator:
  map_width: 8
  map_height: 8
  num_keys: 1

deconv:
  n_filters: 32
  kernel_size: 3
  stride: 1
  padding: 1
  output_padding: 0
  activation: relu
  batch_norm: True
  dropout: 0.0

base:
  n_filters: 32
  kernel_size: 3
  stride: 1
  padding: 1
  activation: relu
  batch_norm: True
  dropout: 0.0